version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: youtube-backend
    ports:
      - "8081:8000"
    env_file:
      - .env  # ✅ Load your API keys securely into the container
    networks:
      - analyzer-network
    volumes:
      - ./assets/pdfs:/app/assets/pdfs

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: youtube-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - analyzer-network
    volumes:
      - ./assets/pdfs:/app/assets/pdfs

networks:
  analyzer-network:
    driver: bridge
